# **EXERCISE 1**


 L'analyse de données est un processus d' inspection , de nettoyage , de transformation
 et de modélisation des données visant à en extraire des informations utiles, à éclairer
 les conclusions et à faciliter la prise de décision. Ce processus fait appel à diverses
 techniques et outils, allant de l'analyse statistique de base aux algorithmes complexes
 et aux modèles prédictifs .

 Elle joue un rôle crucial dans divers domaines tels que le commerce, les sciences, l'ingénierie
 et les sciences sociales, permettant aux organisations et aux individus de prendre des
 décisions fondées sur les données. Aujourd'hui, l'analyse des données est bien plus qu'un simple
 processus : c'est une nécessité pour une prise de décision éclairée et une planification stratégique.
 Son importance s'étend à :

Stratégie d'entreprise : Aider les entreprises à prendre des décisions fondées sur les données.
Recherche scientifique : Contribuer à la vérification des hypothèses et à la découverte.
Politiques publiques : Contribuer à l'élaboration de politiques fondées sur des données probantes.

Elle est omniprésente dans tous les domaines de la vie aujourd'hui à l'instar de la santé, la finance
 et même de l'agriculture.
En plus, les tendances actuelles en matière d’analyse de données montrent une transformation rapide du
 domaine sous l’effet de l’intelligence artificielle, du cloud computing et de l’explosion des
 données en temps réel. L’IA générative et l’IA agentique occupent désormais une place centrale dans
 les stratégies analytiques des entreprises. Selon Gartner, les agents d’IA capables d’automatiser l’analyse
 et certaines prises de décision représentent l’une des tendances majeures de 2025. gartner.com

Une autre tendance importante est la démocratisation de l’analyse des données. Grâce aux interfaces en
langage naturel et aux outils d’analytics augmentés par l’IA, les utilisateurs non techniques peuvent désormais
 interagir avec les données plus facilement. Les plateformes analytiques utilisent le traitement automatique du
 langage naturel (NLP) afin de permettre des requêtes conversationnelles et la génération automatique d’insights.

L’analyse en temps réel et l’edge analytics gagnent également en importance avec le développement massif des
objets connectés (IoT). Au lieu d’envoyer toutes les données vers des centres cloud centralisés, les entreprises
analysent les données directement à la périphérie du réseau afin de réduire la latence et d’améliorer la rapidité
 de décision. Cette approche est particulièrement utilisée dans l’industrie, les villes intelligentes, la santé et
  les véhicules autonomes.

Par ailleurs, les organisations investissent fortement dans la gouvernance et la qualité des données. Avec l’essor
 de l’IA, la fiabilité des modèles dépend directement de la qualité des données utilisées. Les concepts de
 « data mesh » et de « data as a product » deviennent populaires car ils permettent une gestion décentralisée et
 plus agile des données au sein des grandes entreprises.

Des exemples concrets illustrent ces évolutions. Dans le secteur de la santé, l’analyse de données aide au
diagnostic assisté par IA et à la prédiction de maladies. Dans la finance, les banques utilisent l’analytics
 prédictif pour détecter les fraudes et évaluer les risques en temps réel. Les entreprises de commerce électronique
  exploitent l’IA pour personnaliser les recommandations clients et optimiser les chaînes logistiques. Les usines
  intelligentes, quant à elles, utilisent l’analyse en périphérie pour surveiller les machines et prévenir les pannes
   avant qu’elles ne surviennent.

Enfin, les enjeux éthiques et réglementaires prennent une importance croissante. Les entreprises doivent désormais
garantir la transparence des algorithmes, protéger les données personnelles et mettre en place des pratiques d’IA
responsable afin de respecter les réglementations comme le RGPD.

In [ ]:
#Exercise 2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
drive_path = '/content/drive/MyDrive/Colab Notebooks/'

clean_data = pd.read_csv(drive_path + 'clean_dataset.csv')
Mental_health = pd.read_csv(drive_path + 'Mental health Depression disorder Data.csv')
crx = pd.read_csv(drive_path + 'crx.csv')
Time_Americans = pd.read_csv(drive_path + 'Time Americans Spend Sleeping.csv')
Time_Americans = Time_Americans.head()
print(Time_Americans)
crx = crx.head()
print(crx)
Mental_health = Mental_health.head()
print(Mental_health)
clean_data = clean_data.head()
print(clean_data)

/tmp/ipykernel_4871/2923904707.py:9: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  Mental_health = pd.read_csv(drive_path + 'Mental health Depression disorder Data.csv')

   index  Year  Period  Avg hrs per day sleeping  Standard Error Type of Days  \
0      0  2003  Annual                      8.57           0.018     All days
1      1  2004  Annual                      8.55           0.026     All days
2      2  2005  Annual                      8.62           0.023     All days
3      3  2006  Annual                      8.63           0.024     All days
4      4  2007  Annual                      8.57           0.024     All days

           Age Group  Activity   Sex
0  15 years and over  Sleeping  Both
1  15 years and over  Sleeping  Both
2  15 years and over  Sleeping  Both
3  15 years and over  Sleeping  Both
4  15 years and over  Sleeping  Both
   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +
   index       Entity Code  Year Schizophrenia (%) Bipolar disorder (%)  \
0      0  Afghanistan  AFG  1990           0.16056             0.697779
1      1  Afghanistan  AFG  1991          0.160312             0.697961
2      2  Afghanistan  AFG  1992          0.160135             0.698107
3      3  Afghanistan  AFG  1993          0.160037             0.698257
4      4  Afghanistan  AFG  1994          0.160022             0.698469

  Eating disorders (%)  Anxiety disorders (%)  Drug use disorders (%)  \
0             0.101855               4.828830                1.677082
1             0.099313               4.829740                1.684746
2             0.096692               4.831108                1.694334
3             0.094336               4.830864                1.705320
4             0.092439               4.829423                1.716069

   Depression (%)  Alcohol use disorders (%)
0        4.071831                   0.672404
1        4.079531                   0.671768
2        4.088358                   0.670644
3        4.096190                   0.669738
4        4.099582                   0.669260
   Gender    Age   Debt  Married  BankCustomer     Industry Ethnicity  \
0       1  30.83  0.000        1             1  Industrials     White
1       0  58.67  4.460        1             1    Materials     Black
2       0  24.50  0.500        1             1    Materials     Black
3       1  27.83  1.540        1             1  Industrials     White
4       1  20.17  5.625        1             1  Industrials     White

   YearsEmployed  PriorDefault  Employed  CreditScore  DriversLicense  \
0           1.25             1         1            1               0
1           3.04             1         1            6               0
2           1.50             1         0            0               0
3           3.75             1         1            5               1
4           1.71             1         0            0               0

        Citizen  ZipCode  Income  Approved
0       ByBirth      202       0         1
1       ByBirth       43     560         1
2       ByBirth      280     824         1
3       ByBirth      100       3         1
4  ByOtherMeans      120       0         1

In [ ]:
clean_data.info(10)
clean_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          5 non-null      int64
 1   Age             5 non-null      float64
 2   Debt            5 non-null      float64
 3   Married         5 non-null      int64
 4   BankCustomer    5 non-null      int64
 5   Industry        5 non-null      object
 6   Ethnicity       5 non-null      object
 7   YearsEmployed   5 non-null      float64
 8   PriorDefault    5 non-null      int64
 9   Employed        5 non-null      int64
 10  CreditScore     5 non-null      int64
 11  DriversLicense  5 non-null      int64
 12  Citizen         5 non-null      object
 13  ZipCode         5 non-null      int64
 14  Income          5 non-null      int64
 15  Approved        5 non-null      int64
dtypes: float64(3), int64(10), object(3)
memory usage: 772.0+ bytes

,Gender,Age,Debt,Married,BankCustomer,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,ZipCode,Income,Approved
count,5.000000,5.000000,5.000000,5.0,5.0,5.000000,5.0,5.000000,5.000000,5.000000,5.000000,5.00000,5.0
mean,0.600000,32.400000,2.425000,1.0,1.0,2.250000,1.0,0.600000,2.400000,0.200000,149.000000,277.40000,1.0
std,0.547723,15.210569,2.487504,0.0,0.0,1.087221,0.0,0.547723,2.880972,0.447214,92.800862,389.81765,0.0
min,0.000000,20.170000,0.000000,1.0,1.0,1.250000,1.0,0.000000,0.000000,0.000000,43.000000,0.00000,1.0
25%,0.000000,24.500000,0.500000,1.0,1.0,1.500000,1.0,0.000000,0.000000,0.000000,100.000000,0.00000,1.0
50%,1.000000,27.830000,1.540000,1.0,1.0,1.710000,1.0,1.000000,1.000000,0.000000,120.000000,3.00000,1.0
75%,1.000000,30.830000,4.460000,1.0,1.0,3.040000,1.0,1.000000,5.000000,0.000000,202.000000,560.00000,1.0
max,1.000000,58.670000,5.625000,1.0,1.0,3.750000,1.0,1.000000,6.000000,1.000000,280.000000,824.00000,1.0

Nous avons un tableau qui contient 16 colonnes et 690 lignes qui concerne les informations relative a une demande de carte de crédit. On y trouve des informations démographyques, financières.
Nous constatons que la majeure partie des clients est jeune, pas trop endettée et bien rénumérée.

**EXERCICE 3**
Gender: qualitative
Age: quantitative
debt: quantitative
Married: qualitative
BankCustomer: qualitative
Industry: qualitative
Ethnicity: qualitative
YearsEmployed: quantitative
PriorDefault: qualitative
Employed: qualitative
CreditScore: quantitative
DiversLicence: qualitative
Citizen: qualitative
ZipCode: quantitative
Income: quantitative
Approved: qualitative

Les données sont qualitatives lorsqu'elles ne peuvent pas se mesurer, se quantifier, on ne peut pas appliquer la logique des calculs mathématiques dessus, ce qui explique ici pourquoi Industry par exemple est une donnée qualitative.
Par contre les données sont dites quantitatives lorqu'on peut mesurer leurs valeurs et y appliquer les calculs mathématiques des nombres. Exemple Income.

In [ ]:
#Exercice 4
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
Iris = pd.read_csv('Iris.csv')
Iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

-Colonnes quantitatives: SepalLengthCm, SepalWidthCm, PetalLengthCm et PetalLength. Ce sont des valeurs que l'on peut mesurer!
-Colonnes qualitatives: Species. On ne peut pas la mesurer.

In [ ]:
#Exercice 5
import pandas as pd
Time = pd.read_csv('Time.csv')
Time.info()
Time.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     945 non-null    int64
 1   Year                      945 non-null    int64
 2   Period                    945 non-null    object
 3   Avg hrs per day sleeping  945 non-null    float64
 4   Standard Error            945 non-null    float64
 5   Type of Days              945 non-null    object
 6   Age Group                 945 non-null    object
 7   Activity                  945 non-null    object
 8   Sex                       945 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 66.6+ KB

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both
5,5,2008,Annual,8.60,0.023,All days,15 years and over,Sleeping,Both
6,6,2009,Annual,8.67,0.023,All days,15 years and over,Sleeping,Both
7,7,2010,Annual,8.67,0.024,All days,15 years and over,Sleeping,Both
8,8,2011,Annual,8.71,0.026,All days,15 years and over,Sleeping,Both
9,9,2012,Annual,8.73,0.026,All days,15 years and over,Sleeping,Both

Ici, les colonnes potentiellement pertinantes pour un type d'analyse spécifique sont avg hrs per day sleeping, type of days, sex et age group. Car avec ces colonnes on peut essayer d'étudier par exemple quel groupe d'âge dort le plus ou à partir de quel âge on dort le moins; quel sexe, quand ou quelle est la moyenne d'heure par jour que peut dormir tel ou tel, elles peuvent nous permettre donc de suivre une tendance ou de faire une étude comparée!

**Exercice 6** : Identification des types de données
Vous trouverez ci-dessous différentes sources de données. Indiquez si chacune d'elles est un exemple de données structurées ou non structurées.

Les rapports financiers d'une entreprise sont stockés dans un fichier Excel.
Photographies téléchargées sur une plateforme de médias sociaux.
Une collection d'articles de presse sur un site web.
Données d'inventaire dans une base de données relationnelle.
Enregistrements d'entretiens issus d'une étude de marché.

**Réponses** :

-Les données structurées: Les rapports financiers d'une entreprise sont stockés dans un fichier Excel, Données d'inventaire dans une base de données relationnelle.
-Les données non structurées: Photographies téléchargées sur une plateforme de médias sociaux, Une collection d'articles de presse sur un site web, Enregistrements d'entretiens issus d'une étude de marché.

 **Exercice 7** : Exercice de transformation
Pour chacune des sources de données non structurées suivantes, proposez une méthode pour la convertir en données structurées. Justifiez votre choix.

Une série d'articles de blog sur les expériences de voyage.
Enregistrements audio des appels au service client.
Notes manuscrites issues d'une séance de brainstorming.
Un tutoriel vidéo sur la cuisine.

**Réponses** :

 -**Articles de blog sur les expériences de voyage**:  une
méthode proposée est Traitement du Langage Naturel (NLP) avec Reconnaissance d'Entités Nommées (NER) et Analyse de Sentiment car le NLP permet d'extraire automatiquement des données textuelles textuelles complexes pour les transformer en colonnes de base de données. La NER identifie les entités clés (Lieux, Monuments, Hôtels), tandis que l'analyse de sentiment évalue l'expérience (Positive/Négative). Cela convertit un long texte en un tableau propre.
 -**Enregistrements audio du service client**: une méthode possible est le Speech-to-Text (STT) suivie d'une Text Mining (Fouille de données textuelles) car les fichiers audio bruts ne permettent pas de faire des requêtes ou des statistiques. Un outil STT (comme OpenAI Whisper ou Google Cloud Speech-to-Text) transforme l'audio en texte écrit. Une fois le texte obtenu, des algorithmes de classification peuvent catégoriser automatiquement l'appel par Motif ([Facturation | Panne | Résiliation]) et mesurer la Durée de l'appel, générant ainsi des données prêtes pour un tableau de bord de performance (KPI).
 -**Notes manuscrites de brainstorming**: la conversion peut se faire à travers une Reconnaissance Optique de Caractères (OCR intelligente / ICR intégrée à un LLM). Parce que les notes manuscrites combinent du texte difficile à lire et une structure spatiale souvent anarchique (flèches, bulles). Une OCR classique extrait le texte brut, mais un modèle d'IA moderne (ICR) comprend le contexte pour classifier les idées. Les données textuelles sont alors nettoyées et exportées dans une structure claire de type Mind Map numérique ou tableau Kanban avec des colonnes : [Idée principale | Porteur du projet | Priorité].
 -**Tutoriel vidéo sur la cuisine**: on peut le convertir par l'Analyse Multimodale (Extraction audio + Reconnaissance d'objets par Vision par Ordinateur). Une vidéo contient deux flux d'informations indispensables. L'analyse du son (STT) permet de transcrire la recette sous forme d'instructions textuelles. En parallèle, la vision par ordinateur analyse les images pour détecter les Ingrédients visuels et les Ustensiles utilisés. La combinaison des deux permet de générer automatiquement une fiche recette parfaitement structurée : [Nom du plat | Liste des ingrédients | Temps de cuisson | Étapes de préparation].

In [ ]:
#Exercice 8

import pandas as pd
train = pd.read_csv('train.csv')
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#Exercie 9

animaux = {'name':['Lion', 'Chien', 'ver', 'poulet'],
           'catégorie':['Canivore', 'Canivore', 'détritivore', 'omnivore'],
           'Crie':['Rugit','Aboie', 'Muet', 'Chante']}
animaux = pd.DataFrame(animaux)
animaux.to_excel('animaux.xlsx', sheet_name='sheet1')
animaux.to_json('animaux.json')

In [ ]:
#Exerciec 10

import pandas as pd

url = 'https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/posts.zip'

!wget $url

!unzip posts.zip

data = pd.read_json('posts.json')

data.head()

--2026-05-27 08:27:53--  https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/posts.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://media.githubusercontent.com/media/devtlv/Datasets-DA-Bootcamp-2-/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data%2C%20Exporting%20D/posts.zip [following]
--2026-05-27 08:27:54--  https://media.githubusercontent.com/media/devtlv/Datasets-DA-Bootcamp-2-/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data%2C%20Exporting%20D/posts.zip
Resolving media.githubusercontent.com (media.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to media.githubusercontent.com (media.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7245 (7.1K) [application/zip]
Saving to: ‘posts.zip’

posts.zip           100%[===================>]   7.08K  --.-KB/s    in 0s

2026-05-27 08:27:54 (77.7 MB/s) - ‘posts.zip’ saved [7245/7245]

Archive:  posts.zip
replace posts.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: posts.json

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...